"""empty message

Revision ID: 46abe8e2475b
Revises: bff4af38f7b4
Create Date: 2025-08-12 09:37:30.497287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46abe8e2475b'
down_revision: Union[str, Sequence[str], None] = 'bff4af38f7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False, comment='用户token'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='token过期时间'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=True)
    op.drop_index(op.f('ix_login_token'), table_name='login')
    op.drop_table('login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=20), nullable=False, comment='用户token'),
    sa.Column('expire_time', mysql.DATETIME(), nullable=True, comment='token过期时间'),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='用户ID'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_login_token'), 'login', ['token'], unique=True)
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
