"""empty message

Revision ID: 291c7536e9a1
Revises: 3906ad0b2a63
Create Date: 2025-08-08 22:53:09.275261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '291c7536e9a1'
down_revision: Union[str, Sequence[str], None] = '3906ad0b2a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'content',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_comment='文章内容',
               existing_nullable=True)
    op.drop_index(op.f('ix_postscategory_name'), table_name='postscategory')
    op.create_index(op.f('ix_postscategory_name'), 'postscategory', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postscategory_name'), table_name='postscategory')
    op.create_index(op.f('ix_postscategory_name'), 'postscategory', ['name'], unique=False)
    op.alter_column('comment', 'content',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=80),
               existing_comment='文章内容',
               existing_nullable=True)
    # ### end Alembic commands ###
