"""empty message

Revision ID: 5e6a9a78d439
Revises: 821239b02de6
Create Date: 2025-08-13 18:52:28.128516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e6a9a78d439'
down_revision: Union[str, Sequence[str], None] = '821239b02de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'income',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_comment='收入',
               existing_nullable=True)
    op.alter_column('record', 'spend',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_comment='支出',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'spend',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='支出',
               existing_nullable=True)
    op.alter_column('record', 'income',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='收入',
               existing_nullable=True)
    # ### end Alembic commands ###
