"""empty message

Revision ID: ad56bb7e87c9
Revises: 3d6f2793e583
Create Date: 2025-08-08 22:15:33.106483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad56bb7e87c9'
down_revision: Union[str, Sequence[str], None] = '3d6f2793e583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False, comment='文章标题'),
    sa.Column('content', sa.String(length=80), nullable=False, comment='文章内容'),
    sa.Column('status', sa.Boolean(), server_default='1', nullable=True, comment='是否发布'),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=True, comment='文章可见范围'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='专栏ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_category_id'), 'article', ['category_id'], unique=False)
    op.create_index(op.f('ix_article_status'), 'article', ['status'], unique=False)
    op.create_index(op.f('ix_article_user_id'), 'article', ['user_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=80), nullable=True, comment='文章内容'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='评论者姓名'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='被评论的文章ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_article_id'), 'comment', ['article_id'], unique=False)
    op.create_index(op.f('ix_comment_created_at'), 'comment', ['created_at'], unique=False)
    op.create_table('postscategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='专栏名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postscategory_name'), 'postscategory', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postscategory_name'), table_name='postscategory')
    op.drop_table('postscategory')
    op.drop_index(op.f('ix_comment_created_at'), table_name='comment')
    op.drop_index(op.f('ix_comment_article_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_article_user_id'), table_name='article')
    op.drop_index(op.f('ix_article_status'), table_name='article')
    op.drop_index(op.f('ix_article_category_id'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
