"""empty message

Revision ID: f8ce0e25cb1a
Revises: 86bb479bc437
Create Date: 2025-08-14 23:21:52.978051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f8ce0e25cb1a'
down_revision: Union[str, Sequence[str], None] = '86bb479bc437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_path'), table_name='file')
    op.drop_column('file', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('path', mysql.VARCHAR(length=250), nullable=False, comment='文件路径'))
    op.create_index(op.f('ix_file_path'), 'file', ['path'], unique=True)
    # ### end Alembic commands ###
