"""empty message

Revision ID: 59ee90fbfbbd
Revises: 3257f0734c05
Create Date: 2025-08-13 19:04:23.245024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59ee90fbfbbd'
down_revision: Union[str, Sequence[str], None] = '3257f0734c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'income',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='收入',
               existing_nullable=True)
    op.alter_column('record', 'spend',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='支出',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'spend',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='支出',
               existing_nullable=True)
    op.alter_column('record', 'income',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='收入',
               existing_nullable=True)
    # ### end Alembic commands ###
