"""empty message

Revision ID: dbea9e6f389c
Revises: 97b4b6ad21d7
Create Date: 2025-08-28 10:43:55.001721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbea9e6f389c'
down_revision: Union[str, Sequence[str], None] = '97b4b6ad21d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_course', 'student_course', ['user_id', 'course_id'], unique=True)
    op.create_foreign_key(None, 'student_course', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'student_course', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.drop_index('idx_user_course', table_name='student_course')
    # ### end Alembic commands ###
