"""empty message

Revision ID: 9a045fb72022
Revises: 59ee90fbfbbd
Create Date: 2025-08-13 19:08:17.237945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a045fb72022'
down_revision: Union[str, Sequence[str], None] = '59ee90fbfbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'income',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_comment='收入',
               existing_nullable=True)
    op.alter_column('record', 'spend',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_comment='支出',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'spend',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='支出',
               existing_nullable=True)
    op.alter_column('record', 'income',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='收入',
               existing_nullable=True)
    # ### end Alembic commands ###
