"""empty message

Revision ID: c132f1e028ce
Revises: dbea9e6f389c
Create Date: 2025-08-28 11:46:16.099948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c132f1e028ce'
down_revision: Union[str, Sequence[str], None] = 'dbea9e6f389c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_course_course_id'), 'student_course', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_course_user_id'), 'student_course', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_course_user_id'), table_name='student_course')
    op.drop_index(op.f('ix_student_course_course_id'), table_name='student_course')
    # ### end Alembic commands ###
