"""empty message

Revision ID: 97b4b6ad21d7
Revises: 0c3161127b8f
Create Date: 2025-08-28 10:25:40.395475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b4b6ad21d7'
down_revision: Union[str, Sequence[str], None] = '0c3161127b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_course_ibfk_1'), 'student_course', type_='foreignkey')
    op.drop_constraint(op.f('student_course_ibfk_2'), 'student_course', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('student_course_ibfk_2'), 'student_course', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('student_course_ibfk_1'), 'student_course', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###
