"""empty message

Revision ID: 6d96e10021b0
Revises: 006dc2d74836
Create Date: 2025-08-14 18:32:37.170252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d96e10021b0'
down_revision: Union[str, Sequence[str], None] = '006dc2d74836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='文件名'),
    sa.Column('path', sa.String(length=250), nullable=False, comment='文件路径'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=True)
    op.create_index(op.f('ix_file_path'), 'file', ['path'], unique=True)
    op.create_index(op.f('ix_file_user_id'), 'file', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_user_id'), table_name='file')
    op.drop_index(op.f('ix_file_path'), table_name='file')
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
