"""empty message

Revision ID: 6bf6dcddfb39
Revises: 46abe8e2475b
Create Date: 2025-08-12 17:52:55.183125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6bf6dcddfb39'
down_revision: Union[str, Sequence[str], None] = '46abe8e2475b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'expire_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='token过期时间')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'expire_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='token过期时间')
    # ### end Alembic commands ###
