"""empty message

Revision ID: b8ee4140f00a
Revises: 6bf6dcddfb39
Create Date: 2025-08-13 17:37:17.686440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ee4140f00a'
down_revision: Union[str, Sequence[str], None] = '6bf6dcddfb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='收支分类名称'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_name'), 'expense', ['name'], unique=True)
    op.create_index(op.f('ix_expense_user_id'), 'expense', ['user_id'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=True, comment='收入'),
    sa.Column('spend', sa.Float(), nullable=True, comment='支出'),
    sa.Column('record_time', sa.DateTime(), nullable=False, comment='记录时间'),
    sa.Column('expense_id', sa.Integer(), nullable=False, comment='收支分类ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_expense_id'), 'record', ['expense_id'], unique=False)
    op.create_index(op.f('ix_record_income'), 'record', ['income'], unique=False)
    op.create_index(op.f('ix_record_record_time'), 'record', ['record_time'], unique=False)
    op.create_index(op.f('ix_record_spend'), 'record', ['spend'], unique=False)
    op.create_index(op.f('ix_record_user_id'), 'record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_user_id'), table_name='record')
    op.drop_index(op.f('ix_record_spend'), table_name='record')
    op.drop_index(op.f('ix_record_record_time'), table_name='record')
    op.drop_index(op.f('ix_record_income'), table_name='record')
    op.drop_index(op.f('ix_record_expense_id'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_expense_user_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_name'), table_name='expense')
    op.drop_table('expense')
    # ### end Alembic commands ###
