"""empty message

Revision ID: fb0946972036
Revises: 7713099c9723
Create Date: 2025-08-11 11:18:22.297289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0946972036'
down_revision: Union[str, Sequence[str], None] = '7713099c9723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False, comment='用户token'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='token过期时间'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_token'), 'login', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_token'), table_name='login')
    op.drop_table('login')
    # ### end Alembic commands ###
