"""empty message

Revision ID: 3906ad0b2a63
Revises: ad56bb7e87c9
Create Date: 2025-08-08 22:46:56.898146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3906ad0b2a63'
down_revision: Union[str, Sequence[str], None] = 'ad56bb7e87c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.Text(),
               existing_comment='文章内容',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=80),
               existing_comment='文章内容',
               existing_nullable=False)
    # ### end Alembic commands ###
