"""empty message

Revision ID: 821239b02de6
Revises: b8ee4140f00a
Create Date: 2025-08-13 18:25:30.212164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '821239b02de6'
down_revision: Union[str, Sequence[str], None] = 'b8ee4140f00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'income',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='收入',
               existing_nullable=True)
    op.alter_column('record', 'spend',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='支出',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'spend',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='支出',
               existing_nullable=True)
    op.alter_column('record', 'income',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='收入',
               existing_nullable=True)
    # ### end Alembic commands ###
