"""empty message

Revision ID: 3d6f2793e583
Revises: 
Create Date: 2025-08-08 22:00:27.961358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6f2793e583'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='todo名称'),
    sa.Column('done', sa.Boolean(), server_default='0', nullable=False, comment='是否完成'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_done'), 'todo', ['done'], unique=False)
    op.create_index(op.f('ix_todo_name'), 'todo', ['name'], unique=False)
    op.create_index(op.f('ix_todo_user_id'), 'todo', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='用户名'),
    sa.Column('age', sa.Integer(), nullable=False, comment='年龄'),
    sa.Column('gender', sa.Integer(), nullable=False, comment='性别 1:男,2:女'),
    sa.Column('email', sa.String(length=80), nullable=False, comment='邮箱'),
    sa.Column('password', sa.String(length=80), nullable=False, comment='密码'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_todo_user_id'), table_name='todo')
    op.drop_index(op.f('ix_todo_name'), table_name='todo')
    op.drop_index(op.f('ix_todo_done'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
