"""empty message

Revision ID: 3257f0734c05
Revises: 5e6a9a78d439
Create Date: 2025-08-13 18:58:32.806132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3257f0734c05'
down_revision: Union[str, Sequence[str], None] = '5e6a9a78d439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'income',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               type_=sa.Float(),
               existing_comment='收入',
               existing_nullable=True)
    op.alter_column('record', 'spend',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               type_=sa.Float(),
               existing_comment='支出',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'spend',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=4),
               existing_comment='支出',
               existing_nullable=True)
    op.alter_column('record', 'income',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=4),
               existing_comment='收入',
               existing_nullable=True)
    # ### end Alembic commands ###
