"""empty message

Revision ID: ce6e4515a780
Revises: eb8fd357f80f
Create Date: 2025-08-14 10:02:38.491690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce6e4515a780'
down_revision: Union[str, Sequence[str], None] = 'eb8fd357f80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'income',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='收入')
    op.alter_column('record', 'spend',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='支出')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'spend',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='支出')
    op.alter_column('record', 'income',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='收入')
    # ### end Alembic commands ###
